### ISSUE TITLE
Subscribe to firebase auth state

### ISSUE THREAD

**Issue by mason-smith** [hector4213/coronaviruscanada#1]
@hector4213 

RE: https://www.reddit.com/r/reduxjs/comments/mlu0i5/using_firebase_for_authentication_and_rtk/

~I created a branch but don't have permission to access this repository. Any chance you could hook it up with some temporary permissions?~

~`remote: Permission to hector4213/coronaviruscanada.git denied to mason-smith.
fatal: unable to access 'https://github.com/hector4213/coronaviruscanada.git/': The requested URL returned error: 403`~

Just kidding I'm dumb. Please find [PR here](https://github.com/hector4213/coronaviruscanada/pull/2)

**Comment by mason-smith** [comment]
NOTE: Reddit has crappy MD for code blocks, but the crux of the change looks like this: 
```
useEffect(() => {
  // Listen for auth state changes on component mount
  const unsubscribeFromAuth = auth.onAuthStateChanged((authUser) => {
    if (authUser) {
      // We can update our user if necessary
      createUserProfileDocument(authUser).then((userRef) => {
        userRef.onSnapshot((snapShot) => {
          dispatch(
            setCurrentUser({
              id: snapShot.id,
              ...snapShot.data(),
            }),
          );
        });
      });
    } else {
      // Set it to null
      dispatch(setCurrentUser(authUser));
    }
  });
  return () => {
    // Unsubscribe on component unmount
    unsubscribeFromAuth();
  };
}, []);
```

I put it in a custom hook just for organization purposes

**Comment by hector4213** [comment]
Thanks again, going to review this code and see how it works : )
